// tailwind.config.ts
import type { Config } from 'tailwindcss'

const config: Config = {
  presets: [require("nativewind/preset")],
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './constants/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#131313',
        surface_bright: '#2b2b2f',
        surface_variant: 'rgba(35, 35, 42, 0.72)',
        surface_container_lowest: '#161619',
        surface_container_low: '#1b1b20',
        surface_container: '#202027',
        surface_container_high: '#262630',
        surface_container_highest: '#2d2d39',
        primary: '#d2bbff',
        primary_color_hex: '#6366f1',
        primary_fixed: '#d2bbff',
        primary_container: '#6366f1',
        secondary: '#b8b4c7',
        secondary_container: '#252530',
        tertiary: '#8b5cf6',
        tertiary_container: '#31214d',
        neutral: '#6f7080',
        outline: '#5a5b69',
        outline_variant: '#3a3b46',
        border: '#3a3b46',
        on_primary: '#e5e2e1',
        on_primary_container: '#e5e2e1',
        on_secondary_container: '#e5e2e1',
        on_tertiary_container: '#e5e2e1',
        on_surface: '#e5e2e1',
        on_surface_variant: '#a1a1af',
        on_surface_disabled: '#6f7080',
        error: '#ef4444',
        error_container: '#4a1d1d',
        on_error: '#e5e2e1',
        on_error_container: '#e5e2e1',
        success: '#22c55e',
        success_container: '#163524',
        warning: '#f59e0b',
      },
      fontFamily: {
        regular: ['Inter_400Regular'],
        medium: ['Inter_500Medium'],
        semibold: ['Inter_600SemiBold'],
        bold: ['Inter_700Bold'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.55px' }],
        'body-md': ['14px', { lineHeight: '22px' }],
        'headline-sm': ['24px', { lineHeight: '32px' }],
        'display-md': ['44px', { lineHeight: '48px', letterSpacing: '-0.88px' }],
        xs: ['11px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '18px' }],
        base: ['15px', { lineHeight: '22px' }],
        lg: ['17px', { lineHeight: '24px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['28px', { lineHeight: '36px' }],
      },
      borderRadius: {
        none: '0px',
        sm: '8px',
        DEFAULT: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        full: '999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        'scale-3': '22px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '48px',
      },
      boxShadow: {
        ambient: '0 0 32px rgba(210, 187, 255, 0.04)',
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'spin': 'spin 1s linear infinite',
      },
      keyframes: {
        spin: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
