export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string,
    message: string
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

export const ERROR_CODES = {
  GENERATION_ALREADY_STARTED: 'GENERATION_ALREADY_STARTED',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_IMAGE_BASE64: 'INVALID_IMAGE_BASE64',
  INVALID_IMAGE_FORMAT: 'INVALID_IMAGE_FORMAT',
  INVALID_JOB_ID: 'INVALID_JOB_ID',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_REPLICATE_CONFIG: 'INVALID_REPLICATE_CONFIG',
  INVALID_STYLES: 'INVALID_STYLES',
  INVALID_WEBHOOK_PAYLOAD: 'INVALID_WEBHOOK_PAYLOAD',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;
